### ISSUE TITLE
Rayman Redemption Port

### ISSUE THREAD

**Issue by frenchconnec7ion** [vita-nuova/bounties#175]
Is there any way to port Rymanni’s fan-made game “Rayman Redemption”? It was made for windows but I think there’s an android port in the process and I’m jw if it’s possible. Certainly would need optimization.

**Comment by Rinnegatamante** [comment]
1) This repository is not for port begging, next time you open an issue without a bounty attached you'll get banned.
2) The game is made in GameMaker Studio and uses YYC aka can't be ran with YoYo Loader.
3) No one is porting and will ever port it to Android since the project has been tagged as finished and done since 3 years.
