### ISSUE TITLE
Cavestory Plus Native Psvita Port

### ISSUE THREAD

**Issue by CGG776** [vita-nuova/bounties#19]
The whole reason for this is port is so that we can play cavestory plus on the vita that would be more different than nx engine, to have in a sense, a native cavestory port which never came, now I am not sure if this is possible but I want to see if anyone is interested in porting it.

**Comment by CGG776** [comment]
here is what the wallpaper could be https://cdn02.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_download_software/SQ_NSwitchDS_CaveStoryPlus.jpg 

and the live area bubble could be like this:  https://vignette.wikia.nocookie.net/siivagunner/images/c/ca/Cave_Story.png/revision/latest?cb=20160622021824

again these are just suggestions, and I was hoping it would be like a vita SDK port or something so that we can use the official files of the game to make it run

**Comment by chaoskagami** [comment]
What you're basically asking for is one of the following:

 * Add support for Plus features to CSE2 and port it to the Vita
 * Add support for Plus features to NXengine-evo

For the former, CSE2 is basically dead. Nicalis has already ruled on it being illegal. Distribution of it is impossible, and this isn't gonna happen. It's dead. Let it go.

For the latter, nxengine-evo is already good enough for the most part. It fixes most of the "problems" where nxengine does not behave the same as the original, it supports widescreen, it supports the extra soundtracks from the Switch version if you place the files in the correct location [(see here)](https://github.com/nxengine/nxengine-evo/blob/628923b96e0da44f75e17f56f1f9968f47dc0cc7/data/music_dirs.json), it supports Switch-style strafing (you're welcome, by the way) and uses the far superior fan translation instead of the butchered official one.

If you want Curly mode, difficulty options or multiplayer, you're on your own. You'd be better off taking all those up with nxengine-evo's upstream instead of posting a bounty here.

**Comment by Rinnegatamante** [comment]
Closing the issue since no bounty has been opened linked to it.
