### ISSUE TITLE
The Ur-Quan Masters port for Vita [$30 awarded]

### ISSUE THREAD

**Issue by Siltala** [vita-nuova/bounties#69]
Hi,

This is a bounty for a fully functional (netplay not necessary if it is too difficult, but it would be nice to have) port of the Ur-Quan Masters 0.8.0. For clarity, I note that there exists a separate "Ur-Quan Masters HD" project, but this bounty is explicitly intended for the vanilla game.

The game is open source, and all the game assets are available as freeware - see http://sc2.sourceforge.net/ for the project's website. As far as I am aware, all of the required dependencies are already available for the Vita and the hardware should be more than sufficient - [a functional PSP port was made in 2006](https://www.dcemu.co.uk/vbulletin/threads/20763-Ur-Quan-Masters-0-5-0-PSP-Port-Rev-001) which also runs on Adrenaline, but it is an outdated version and I would much rather have the latest version native to the Vita.

I wouldn't know for sure, but I expect that this will be a relatively simple port to make, overall. I've never dealt with Bountysource before, but I'll try and put some money in there ASAP.

**Comment by argarak** [comment]
hello! i've also wanted a port of uqm to the vita for a while so i've started some development over at: (https://github.com/argarak/uqm-vita)
currently i've managed to get the source code built and linked under vitasdk by modifying dholmes215's cmake build system for uqm (https://github.com/dholmes215/uqm) and also have a working logging system. currently, i still need to modify the filesystem operations to work on the vita, implement the controls how i want them (with absolute positioning using the analogue nubs) and other miscellaneous things like working input dialogues, metadata and the like.
development is going to be pretty sporadic because i have to attend to other work, plus i'm new to working with vitasdk and vita development in general so that will slow me down as well! expect a commit or two a week maybe....
if i get a fully working build i will update the bountysource!

**Comment by Siltala** [comment]
Nice! I'm still around and keeping an eye on this issue, so the bounty from me is not forgotten if you get it to a working state. :)

**Comment by argarak** [comment]
rev1 is now released! this is a playable version with directional joystick support, vita input text dialogs, vita filesystem and other bug fixes. netplay is currently not supported and is planned for rev2. there is currently a gotcha with the 3DO smooth melee mode which results in slowdown, so it is not recommended. you can find a list of options which may not quite work as expected on the repository's README.

please follow the installation instructions at https://github.com/argarak/uqm-vita and let me know if there are any issues! i haven't yet released this port everywhere, but it will be available in the homebrew browser at some point in the near future. i think i updated the bountysource correctly, i'm not too familiar with it

**Comment by Siltala** [comment]
Wonderful, thanks! I got it set up on my Vita with your instructions and everything seems to be working fine so far.
Bountysource's instructions say that you should be able to claim the bounty after this issue is closed. I will do so now, so do feel free to make a claim there. If any issues come up, I'll file issues on your repo.

Thanks again!
